apps/index/urls.py
from django.urls import path
from . import views


app_name = 'index'

urlpatterns = [
    path('main/', views.HomeListView.as_view(), name='main'),
    path('liveRoom/', views.liveRoomView.as_view(), name='liveRoom'),
    path('zhubo/', views.anchor.as_view(), name='zhubo'),
    




]

live/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
# from cpmindex import views as index_views

urlpatterns = [
    # path('', include('cpmindex.urls')),
    path('index/', include('index.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/index/models.py
from django.db import models

# Create your models here.

apps/index/views.py
import datetime
import json
import os
import time
from os import path
import hashlib
import requests
from PIL import Image

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_http_methods
from django.views.generic import View
 
 
 
# @method_decorator(login_required, name='dispatch')
class HomeListView(View):
    '''获取所有可用的直播平台'''
    def pingtai(self):
        url = 'http://api.hclyz.com:81/mf/json.txt'
        response = requests.get(url)
        self.pingtai = json.loads(response.text)['pingtai']
        return self.pingtai
    def get(self, request):
        return render(request,'index/home.html',{'pingtai':self.pingtai})
 
# @method_decorator(login_required, name='dispatch')
class liveRoomView(View):
    '''某个平台下面的存在主播'''
    def get(self, request):
        address = request.GET.get('address')
        title = request.GET.get('title')
        zhubo = str("http://api.hclyz.com:81/mf/" + address)
        response = requests.get(zhubo)
        # print(response.text)
        liveroom = json.loads(response.text)['zhubo']

        return render(request, 'index/liveRoom.html',{"room_title":title,"anchors":liveroom} )
 
# @method_decorator(login_required, name='dispatch')
class anchor(View):
    '''直播视频页面'''
    def get(self, request):
        title1 = request.GET.get('title1')
        title2 = request.GET.get('title2')
        address = request.GET.get('address')
        return render(request, 'index/anchor.html', {'anchor_name':title1,'room_title':title2, 'anchor_address':address})

front/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
</head>
<link crossorigin="anonymous" integrity="sha384-9GKi7Mg3e8wxMnh60bnNnc9kuwGfarF0StF1UbfPt4F5GMVfxBgfh8/pW4iHavxG" href="https://lib.baomitu.com/twitter-bootstrap/3.4.1/css/bootstrap.css" rel="stylesheet">
<style>

</style>
<body>
    <script crossorigin="anonymous" integrity="sha384-BqgdDRqoSM34U92AkJHjlNmbVsfEZStnqGg4pVMc/AMY0XbNFRu3cO5LfJXXXETD" src="https://lib.baomitu.com/twitter-bootstrap/3.4.1/js/bootstrap.js"></script>
   
    {% block breadcrumb%}
    {% endblock %}

    <hr>

    {% block content%}
    {% endblock %}

</body>
</html>

front/templates/index/anchor.html
{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'index:main' %}">返回</a></li>
    <li class="breadcrumb-item active">{{ anchor_name }} -- {{ room_title }}</li>

{% endblock %}
{% block content %}
<div align="center">
    <link rel="stylesheet"  />
    <script charset="utf-8" type="text/javascript" src="https://g.alicdn.com/de/prismplayer/2.8.0/aliplayer-flash-min.js"></script>
    <div  class="prism-player" id="J_prismPlayer"></div>
    <script>
            var player = new Aliplayer({
            id: 'J_prismPlayer',
            width: '400px',
            height:'600px',
            autoplay: true,
            isLive:true,
            snapshot:true,
            //支持播放地址播放,此播放优先级最高
            source : '{{ anchor_address }}'
                });
        </script>
</div>
{% endblock %}

front/templates/index/home.html
{% extends 'base.html' %}
{% block content %}





<div class="row">
    {% for pi in pingtai  %}

    <div class="col-lg-2 col-md-2">
        <div class="media">
            <div class="media-left">
            <a href="{% url 'index:liveRoom'  %}?address={{ pi.address }}&title={{ pi.title }}" >
                
                <img class="media-object" src="{{ pi.xinimg }}" alt{{ pi.title }} width="100" height="100">
            </a>
            
            </div>
            <div class="media-body">
              <h4 class="media-heading">{{ pi.title }}</h4>
              <!-- {{ anchor.address }} -->
            </div>
          </div>
    </div>
    
    {% endfor %}
</div>


{% endblock %}

front/templates/index/liveRoom.html
{% extends 'base.html' %}
   
{% block breadcrumb%}
<li class="breadcrumb-item"><a href="{% url 'index:main' %}">返回</a></li>
<li class="breadcrumb-item active">{{ room_title }}</li>

{% endblock %}


{% block content%}

<div class="row">
    {% for anchor in anchors  %}

    <div class="col-lg-2 col-md-2">
        <div class="media">
            <div class="media-left">
            <a href="{% url 'index:zhubo'%}?title1={{ room_title }}&title2={{ anchor.title  }}&address={{ anchor.address  }}">
                <img class="media-object" src="{{ anchor.img }}" alt="..." width="100" height="100">
              </a>
            </div>
            <div class="media-body">
              <h4 class="media-heading">{{ anchor.title }}</h4>
              <!-- {{ anchor.address }} -->
            </div>
          </div>
    </div>
    
    {% endfor %}
</div>

{% endblock %}